project_id = "ikvwejdepfvjuofcnbww"

[functions.cboe-options]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.ai-bias]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-checkout-public]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

